"""documents.owner_id not null

Revision ID: 13e7548b7c89
Revises: 5a6af93ccaa3
Create Date: 2026-08-20 07:41:25.847046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e7548b7c89'
down_revision: Union[str, Sequence[str], None] = '5a6af93ccaa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite has no ALTER TABLE support for changing a column's nullability
    # in place - batch mode (copy-and-move) is required, same as the FK
    # migration before this one.
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('owner_id', existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('owner_id', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
