"""add document intelligence fields

Revision ID: 3888cbfd214e
Revises: 13e7548b7c89
Create Date: 2026-08-21 19:12:31.789006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3888cbfd214e'
down_revision: Union[str, Sequence[str], None] = '13e7548b7c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('sender_category', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('sender_institution', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('document_type', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('priority_level', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('priority_reasoning', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('deadline_raw_text', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('deadline_type', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('deadline_estimated_date', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('deadline_certainty', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('requires_action', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('action_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'action_summary')
    op.drop_column('documents', 'requires_action')
    op.drop_column('documents', 'deadline_certainty')
    op.drop_column('documents', 'deadline_estimated_date')
    op.drop_column('documents', 'deadline_type')
    op.drop_column('documents', 'deadline_raw_text')
    op.drop_column('documents', 'priority_reasoning')
    op.drop_column('documents', 'priority_level')
    op.drop_column('documents', 'document_type')
    op.drop_column('documents', 'sender_institution')
    op.drop_column('documents', 'sender_category')
    # ### end Alembic commands ###
